// cra/src/App.tsx
import React, { useState } from 'react';
import css from './App.module.css';

export default function App() {
    const [todoList, setTodoList] = useState<string[]>([]);
    const [todoInputValue, setTodoInputValue] = useState<string>('');

    const addNewTodo = (event: React.FormEvent) => {
        event.preventDefault();
        setTodoList([...todoList, todoInputValue]);
        setTodoInputValue('');
    }

    return (
        <div className={css.App}>
            <h1>TODO APP - CRA</h1>
            <ul>
                {todoList.map((todo, index) =>
                    <li key={index}>{todo}</li>
                )}
            </ul>
            <form onSubmit={(event) => addNewTodo(event)} >
                <input
                    placeholder="add todo..."
                    value={todoInputValue}
                    onChange={(event) => setTodoInputValue(event.target.value)}
                />
                <button type="submit">
                    Add
                </button>
            </form>
        </div>
    )
}

// vite-svelte/src/App.svelte
<script lang="ts">
    let todoList: string[] = [];
    let todoInputValue: string = "";

    const addTodo = (event: Event) => {
        event.preventDefault();
        todoList = [...todoList, todoInputValue];
        todoInputValue = "";
    };
</script>

<div class="App">
    <h1>TODO App - Vite Svelte</h1>
    <ul>
        {#each todoList as todo}
            <li>{todo}</li>
        {/each}
    </ul>
    <form on:submit={(event) => addTodo(event)}>
        <input placeholder="add todo..." bind:value={todoInputValue} />
        <button type="submit">add</button>
    </form>
</div>

<style>
    :root {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    }

    .App {
        margin: 30px auto;
        width: fit-content;
    }
</style>
